import Head from "next/head";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import Banner from "../Component/Banner";
import "../styles/Home.module.css";
import CryptoTable from "@/Component/CryptoTable";
import Header from "@/Component/Header";
import Paginate from "@/Component/Paginate";

export default function Home() {
  return (
    <>
      <Head>
        <title>Coin Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <CryptoTable />
      <Paginate />
    </>
  );
}
